export const GET_UPCOMING_EVENTS = 'GET_UPCOMING_EVENTS';
export const UPCOMING_EVENTS_LOADING = 'UPCOMING_EVENTS_LOADING';

export const GET_COMPLETED_EVENTS = 'GET_COMPLETED_EVENTS';
export const COMPLETED_EVENTS_LOADING = 'COMPLETED_EVENTS_LOADING';

export const FIND_INDIV_EVENT = 'FIND_INDIV_EVENT';
export const SET_SELECTED_EVENT = 'SET_SELECTED_EVENT';

export const UPDATE_USER = 'UPDATE_USER';
export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = 'LOGOUT';
export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const PROFILE_LOADING = 'PROFILE_LOADING';

export const ADD_EVENT = 'ADD_EVENT';

export const GET_STALLS = 'GET_STALLS';
export const STALL_LOADING = 'STALL_LOADING';
export const SET_INDIVIDUAL_STALL = 'SET_INDIVIDUAL_STALL';
export const UPDATE_INDIVIDUAL_STALL = 'UPDATE_INDIVIDUAL_STALL';

export const GET_STALL_VISITORS = 'GET_STALL_VISITORS';
export const STALL_VISITOR_LOADING = 'STALL_VISITOR_LOADING';
export const SET_INDIVIDUAL_STALL_VISITOR = 'SET_INDIVIDUAL_STALL_VISITOR';

export const GET_CONFERENCES = 'GET_CONFERENCES';
export const CONFERENCE_LOADING = 'CONFERENCE_LOADING';
export const SET_INDIVIDUAL_CONF = 'SET_INDIVIDUAL_CONF';

export const GET_CONF_VISITORS = 'GET_CONF_VISITORS';
export const CONF_VISITOR_LOADING = 'CONF_VISITOR_LOADING';
export const SET_INDIVIDUAL_CONF_VISITOR = 'SET_INDIVIDUAL_CONF_VISITOR';

export const GET_VISITOR = 'GET_VISITOR';
export const VISITOR_LOADING = 'VISITOR_LOADING';
export const SET_INDIV_VISITOR = 'SET_INDIV_VISITOR';